steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Prisma Cloud 
        id: Prisma Cloud
        uses: bridgecrewio/checkov-action@master 
        env:
          PRISMA_API_URL: https://api.sg.prismacloud.io
        with:
          api-key: bc6d4a2b-b7f6-4451-b2f9-d4bb8ff6d3d1::Kcz9YK8HL8iT6zSEdIo6U3YxMTA=
